version: '3.1'
services:
  # MySQL 5.7 server
  mysql57:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql57
    hostname: mysql57.docker
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - './data:/home'
      - '.mysql/5.7:/var/lib/mysql'
      - '.logs/5.7:/var/log'
      - './config/5.7:/etc/mysql/conf.d'
    ports:
      - 30657:3306

  # MySQL 8.0
  mysql80:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql80
    hostname: mysql80.docker
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - './data:/home'
      - '.mysql/8.0:/var/lib/mysql'
      - '.logs/8.0:/var/log'
      - './config/8.0:/etc/mysql/conf.d'
    ports:
      - 30680:3306
      
  # phpMyAdmin
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
